# Generated by Django 5.1.1 on 2024-11-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_index_page_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='x_icon_Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='X-icon/')),
            ],
        ),
    ]
